version: '3.8'

services:
  # Mem0 MCP Server - Standalone deployment
  mem0-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mem0-mcp-server
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      # Server configuration
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8001
      - MCP_DEBUG=false
      
      # Mem0 service connection (external)
      - MEM0_BASE_URL=${MEM0_BASE_URL:-http://mem0-server:8000}
      - MEM0_API_VERSION=${MEM0_API_VERSION:-v1}
      - MEM0_API_KEY=${MEM0_API_KEY}
      
      # Logging configuration
      - MCP_LOG_LEVEL=${MCP_LOG_LEVEL:-INFO}
      - MCP_LOG_TO_FILE=true
      - MCP_LOG_FILE_PATH=/app/logs/server.log
      
      # Performance settings
      - MCP_MAX_CONCURRENT_REQUESTS=${MCP_MAX_CONCURRENT_REQUESTS:-100}
      - MCP_REQUEST_TIMEOUT=${MCP_REQUEST_TIMEOUT:-30}
      
      # Transport settings
      - MCP_TRANSPORT=http
      - MCP_ENABLE_STREAMING=true
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - mem0-network  # 连接到现有的 mem0 网络
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  mem0-network:
    external: true  # 使用外部已存在的 mem0 网络